apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: guestbook-ui
  deployment: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.2
            memory: 32Mi
          requests:
            cpu: 0.2
            memory: 32Mi
